#!/bin/bash

YLW_B='\033[1;33m'
YLW='\033[0;33m'
GRN='\033[0;32m'
GRN_B='\033[1;32m'
NC='\033[0m' # No Color

# device uptime
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`

# get the load averages
read one five fifteen rest < /proc/loadavg

# get system processes
ACTIVE_PROCS=`ps e | wc -l | tr -d " "`
TOTAL_PROCS=`ps ax | wc -l | tr -d " "`

# get system memory
MEM_FREE=`cat /proc/meminfo | grep MemFree | awk {'print $2/1024'}`
MEM_TOTAL=`cat /proc/meminfo | grep MemTotal | awk {'print $2/1024'}`

# get temperature
TEMP="unknown"
if [[ -f /sys/class/thermal/thermal_zone4/temp ]]; then
  TEMP=`cat /sys/class/thermal/thermal_zone4/temp`
fi

# get HDD space
HDD_USED=`df -kh / | sed -n 2p | awk {'print $3'}`
HDD_TOTAL=`df -kh / | sed -n 2p | awk {'print $2'}`

# get numbers
SERIAL=`dmidecode -s system-serial-number`
PRODUCT_NAME=`dmidecode -s system-product-name`

printf "${YLW_B}"
printf "  ${YLW_B}System ...... :  ${GRN_B}${PRODUCT_NAME} (${SERIAL})\n"
printf "  ${YLW_B}Uptime....... :  ${GRN_B}${UPTIME}\n"
printf "  ${YLW_B}Load avg..... :  ${GRN_B}${one}, ${five}, ${fifteen}, ${rest}\n"
printf "  ${YLW_B}Processes.... :  ${GRN_B}${ACTIVE_PROCS} active / ${TOTAL_PROCS} total\n"
printf "  ${YLW_B}Memory....... :  ${GRN_B}`printf %.1f ${MEM_FREE}`M free / `printf %.1f ${MEM_TOTAL}`M total\n"
printf "  ${YLW_B}HDD Space.... :  ${GRN_B}${HDD_USED} used / ${HDD_TOTAL} total\n"
printf "  ${YLW_B}Temperature.. :  ${GRN_B}`printf %.1f $((TEMP/1000))` °C\n"
printf "${NC}\n"